[window]
padding = { x = 5, y = 5 }
decorations = "Buttonless"
opacity = 0.98

[font]
size = 11.0

[font.normal]
family = "Monaco"

[font.offset]
y = 1

[colors]
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.cursor]
text = "#282c34"
cursor = "#abb2bf"
